### ISSUE TITLE
go install doesn't work

### ISSUE THREAD

**Issue by marcelloh** [gojek/go-coverage#1]
newer programs (such as this tool) should be installed by the command:
go install github.com/gojek/go-coverage@latest
instead of the go get -u variant

But if i do that, there is something wrong:
go: downloading github.com/gojek/go-coverage v0.0.1
go install: github.com/gojek/go-coverage@latest: github.com/gojek/go-coverage@v0.0.1: parsing go.mod:
        module declares its path as: github.com/gojekfarm/go-coverage
                but was required as: github.com/gojek/go-coverage
                
Great idea for that tool BTW :-)

**Comment by mpontillo** [comment]
I got it working using:
```
go get -u github.com/gojekfarm/go-coverage
```
(but I think you are correct that I should have used `go install`; this `go get` command actually changed the `go.mod` and `go.sum` files inside the project I was working on 😅)

**Comment by mpontillo** [comment]
Oddly enough I have the opposite problem when working with this repository on GitHub; when I browse to [`https://github.com/gojekfarm/go-coverage`](https://github.com/gojekfarm/go-coverage) it redirects here (`https://github.com/gojek/go-coverage`).

**Comment by muhfaris** [comment]
hi @marcelloh you can try to change the repo URL
```
❯ go install github.com/gojekfarm/go-coverage@latest
```

**Comment by MarcelXia** [comment]
this works :-) thanks.
